# start from the rocker/r-ver:3.5.0 image
FROM rocker/r-ver:3.6.3

# install the linux libraries needed for plumber
RUN apt-get update 
RUN apt-get install -y \
  cron \
  libssl-dev \
  libxml2-dev \
  libcurl4-gnutls-dev \
  libpng-dev

COPY .Renviron .Renviron

RUN R -e "install.packages('remotes', repos = c(CRAN =  'http://cloud.r-project.org'))"
RUN R -e "remotes::install_github('rstudio/renv@0.15.5')"

#Python
RUN apt-get update
RUN apt-get install python3 python3-dev python3-pip -y
COPY requirements.txt requirements.txt
RUN python3 -m pip install -r requirements.txt

#dependencias de rJava
RUN apt-get -y update && apt-get install -y \
   default-jdk \
   r-cran-rjava \
   && apt-get clean \
   && rm -rf /var/lib/apt/lists/
   
COPY local_pkg local_pkg
COPY renv.lock renv.lock
COPY renv renv

RUN R -e "source('renv/activate.R')"
RUN R -e "renv::restore()"

RUN R -e "install.packages('plumber')"
RUN R -e "install.packages('cronR')"

# open port 80 to traffic
EXPOSE 80
EXPOSE 81

CMD Rscript /plumber/main.R
